import type { Color } from './podTypes';

export const VARIATION_COLORS: Color[] = [
  { name: "Black", value: "BLACK", hex: "#000000" },
  { name: "White", value: "WHITE", hex: "#FFFFFF" },
  { name: "Sport Grey", value: "SPORT GREY", hex: "#a9a9a9" },
  { name: "Dark Heather", value: "DARK HEATHER", hex: "#424242" },
  { name: "Navy", value: "NAVY", hex: "#000080" },
  { name: "Red", value: "RED", hex: "#FF0000" },
  { name: "Royal Blue", value: "ROYAL BLUE", hex: "#4169E1" },
  { name: "Purple", value: "PURPLE", hex: "#800080" },
  { name: "Orange", value: "ORANGE", hex: "#FFA500" },
  { name: "Ash", value: "ASH", hex: "#C0C0C0" },
  { name: "Charcoal", value: "CHARCOAL", hex: "#36454F" },
  { name: "Forest Green", value: "FOREST GREEN", hex: "#228B22" },
  { name: "Irish Green", value: "IRISH GREEN", hex: "#009E60" },
  { name: "Light Blue", value: "LIGHT BLUE", hex: "#ADD8E6" },
  { name: "Light Pink", value: "LIGHT PINK", hex: "#FFB6C1" },
  { name: "Maroon", value: "MAROON", hex: "#800000" },
  { name: "Military Green", value: "MILITARY GREEN", hex: "#4B5320" },
  { name: "Sand", value: "SAND", hex: "#C2B280" },
  { name: "Sapphire", value: "SAPPHIRE", hex: "#0F52BA" },
  { name: "Gold", value: "GOLD", hex: "#FFD700" },
  { name: "Carolina Blue", value: "CAROLINA BLUE", hex: "#4B9CD3" },
  { name: "Daisy", value: "DAISY", hex: "#F8DE7E" },
  { name: "Dark Chocolate", value: "DARK CHOCOLATE", hex: "#490206" },
  { name: "Heliconia", value: "HELICONIA", hex: "#DB0F66" },
  { name: "Indigo Blue", value: "INDIGO BLUE", hex: "#00416A" },
  { name: "Kiwi", value: "KIWI", hex: "#8EE53F" },
  { name: "Orange", value: "ORANGE", hex: "#FFA500" },
  { name: "Safety Green", value: "SAFETY GREEN", hex: "#CCFF00" },
  { name: "Safety Orange", value: "SAFETY ORANGE", hex: "#FF6700" },
  { name: "Safety Pink", value: "SAFETY PINK", hex: "#FF69B4" },
  { name: "Sky", value: "SKY", hex: "#87CEEB" },
  { name: "Violet", value: "VIOLET", hex: "#8F00FF" },
  { name: "Yellow Haze", value: "YELLOW HAZE", hex: "#FCE205" },
];